#!/bin/sh

set -e

PGPASSWORD="$APP_DB_ADMIN_PASS" psql -v ON_ERROR_STOP=1 --username "$APP_DB_ADMIN_USER" <<-EOSQL
    CREATE DATABASE $APP_DB_NAME;
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
EOSQL