version: '3.2'

services:
  db:
    image: postgres:${APP_DB_IMAGE_VERSION:-13}
    env_file: .env
    restart: always
    ports:
      - ${APP_DB_PORT}:5432
    volumes:
      - ./etc/db/init.d:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${APP_DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${APP_DB_ADMIN_PASS}

  app:
    image: craft-beer:latest
    build: .
    env_file: .env
    ports:
      - ${APP_PORT:-9000}:${APP_PORT:-9000}
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}

volumes:
  db_data:
