server:
  port: "${APP_PORT:9000}"
  servlet:
    context-path: '${APP_PATH:@app.context-path@}'

spring:
  datasource:
    platform: '${APP_DB_PLATFORM:@app.db.platform@}'
    url: '${APP_DB_URL:@app.db.url@}'
    username: '${APP_DB_USER:@app.db.user@}'
    password: '${APP_DB_PASS:@app.db.pass@}'
